#!/bin/bash
# tablet-verify.sh — verify-only health check for the tablet + OSK stack.
# Read-only by default (exit 0 = healthy, exit 1 = problems found).
# With --fix: re-apply ONLY mechanical repairs (require line, exec bits).
# Never rewrites binding semantics — owned-lua content stays yours.
set -u

HYPR="$HOME/.config/hypr"
FAIL=0

pass() { echo "PASS: $1"; }
fail() { echo "FAIL: $1"; FAIL=1; }

grep_q() { grep -qF "$1" "$2" 2>/dev/null; }

# --- 1. Owned-lua markers (what refresh-hyprland overwrites) ---
if grep_q 'require("hypr.tablet")' "$HYPR/hyprland.lua"; then
  pass "hyprland.lua requires hypr.tablet"
else
  fail "hyprland.lua missing require(\"hypr.tablet\")"
  if [[ "${1:-}" == "--fix" ]]; then
    # Appended at EOF (original sits ~line 21); equivalent — tablet.lua
    # is self-contained (boot cleanup + no_focus rules, no ordering deps).
    echo 'require("hypr.tablet")' >> "$HYPR/hyprland.lua"
    echo "FIXED: require line re-appended"
  fi
fi

if grep_q 'tablet-mode.sh toggle' "$HYPR/bindings.lua" && \
   grep_q 'osk-toggle.sh' "$HYPR/bindings.lua"; then
  pass "bindings.lua tablet + OSK binds present"
else
  fail "bindings.lua tablet/OSK binds missing (manual restore — semantics, not mechanical)"
fi

if grep_q 'natural_scroll = true' "$HYPR/input.lua" && \
   grep_q 'disable_while_typing = false' "$HYPR/input.lua"; then
  pass "input.lua touchpad settings present"
else
  fail "input.lua touchpad settings missing (manual restore)"
fi

[[ -f "$HYPR/tablet.lua" ]] \
  && pass "tablet.lua present" \
  || fail "tablet.lua missing"

# --- 2. Scripts executable ---
for s in tablet-mode.sh tablet-modwait.py tablet-auto-exit.py touch-gestures.sh \
         auto-rotate.sh touch-cursor.py osk-toggle.sh custom-kbd.py custom-kbd-toggle.sh; do
  if [[ -x "$HYPR/scripts/$s" ]]; then
    pass "exec $s"
  else
    fail "not executable: $s"
    if [[ "${1:-}" == "--fix" && -f "$HYPR/scripts/$s" ]]; then
      chmod +x "$HYPR/scripts/$s" && echo "FIXED: chmod +x $s"
    fi
  fi
done

# --- 3. State + layout sanity ---
BACKEND="$(cat "$HOME/.local/state/omarchy/toggles/hypr/osk-backend" 2>/dev/null || echo custom)"
case "$BACKEND" in
  custom) pass "osk-backend=$BACKEND" ;;
  squeekboard|wvkbd) echo "WARN: osk-backend=$BACKEND (deliberate fallback — installer default is custom)" ;;
  *) fail "osk-backend invalid: $BACKEND" ;;
esac

if python3 -c "import json;json.load(open('$HYPR/kbd-layouts/en.json'))" 2>/dev/null; then
  pass "en.json parses"
else
  fail "en.json invalid JSON"
fi

# --- 3.5 Device detection (generic; report + warn, --fix regenerates) ---
if source "$HYPR/scripts/tablet-devices.sh" 2>/dev/null; then
  if [[ -n $TABLET_FINGER ]]; then
    pass "touch device detected: $TABLET_FINGER"
  else
    echo "WARN: no touch device detected — pin one in $HYPR/tablet-devices.conf"
  fi
  [[ -n $TABLET_OUTPUT ]] && pass "internal display detected: $TABLET_OUTPUT" \
    || echo "WARN: no internal display detected"
else
  fail "tablet-devices.sh missing or broken"
fi

if [[ -f "$HYPR/tablet-devices.lua" ]]; then
  luac -p "$HYPR/tablet-devices.lua" 2>/dev/null && pass "tablet-devices.lua parses" \
    || fail "tablet-devices.lua invalid"
else
  echo "WARN: tablet-devices.lua missing"
  if [[ "${1:-}" == "--fix" && -x "$HYPR/scripts/tablet-devices.sh" ]]; then
    (source "$HYPR/scripts/tablet-devices.sh";
     printf -- '-- GENERATED by tablet-kbd install.sh — device names for tablet.lua.\nreturn { finger = "%s", output = "%s" }\n' "$TABLET_FINGER" "$TABLET_OUTPUT" > "$HYPR/tablet-devices.lua") \
      && luac -p "$HYPR/tablet-devices.lua" 2>/dev/null && echo "FIXED: tablet-devices.lua regenerated"
  fi
fi

# --- 4. Systemd units enabled ---
for u in auto-rotate.service lisgd-gestures.service touch-cursor.service; do
  if systemctl --user is-enabled "$u" >/dev/null 2>&1; then
    pass "unit enabled $u"
  else
    fail "unit not enabled: $u"
  fi
done

# --- 5. Bar toggle placement (warn-only: user may move it deliberately) ---
if python3 -c "
import json,sys
cfg=json.load(open('$HOME/.config/omarchy/shell.json'))
blob=json.dumps(cfg)
sys.exit(0 if 'io.github.ngek202.tablet-toggle' in blob else 1)" 2>/dev/null; then
  pass "toggle widget placed in bar"
else
  echo "WARN: toggle widget id not found in shell.json (ok if moved/removed deliberately)"
fi

if [[ "$FAIL" -eq 0 ]]; then
  echo "tablet-verify: ALL GREEN"
else
  echo "tablet-verify: PROBLEMS FOUND (run with --fix for mechanical repairs)"
fi

# --- 6. Fallback coexistence (INFO only — never FAIL) ---
command -v squeekboard >/dev/null 2>&1 \
  && echo "INFO: fallback present: squeekboard (select via OSK_BACKEND=squeekboard)" \
  || echo "INFO: fallback absent: squeekboard (optional safety net: sudo pacman -S squeekboard)"
if command -v wvkbd >/dev/null 2>&1 || command -v wvkbd-mobintl >/dev/null 2>&1; then
  echo "INFO: fallback present: wvkbd (select via OSK_BACKEND=wvkbd)"
else
  echo "INFO: fallback absent: wvkbd (optional safety net: sudo pacman -S wvkbd)"
fi
exit "$FAIL"
